import { isTruthy } from "./utils";



/**
 * Parse domain names from a list of Traefic router rules in a text file.
 * This file is expected to be generated by docker-gen, using the `traefic_rules.tpl.txt` file.
 */
export async function parseTraeficDomains(ruleFile: Blob): Promise<string[]> {
    const ruleData = await ruleFile.text();
    return ruleData.split(/[\n\r]+/)
        .map((line) => /Host\(`([^`]+)`\)/.exec(line)?.[1])
        .filter(isTruthy)
        .filter((host, i, arr) => arr.indexOf(host) === i);
}

/**
 * Parse a simple list of domain names from a file.
 * Domains are expected to be one-per-line.
 */
export async function parseDomains(file: Blob): Promise<string[]> {
    const filedata = await file.text();
    return filedata.split(/[\n\r]+/)
        .map((line) => line.trim())
        .filter(isTruthy);
}
